# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-03 09:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acctNumber', models.PositiveIntegerField()),
                ('brokerName', models.CharField(max_length=32)),
                ('closeUp', models.DecimalField(decimal_places=2, max_digits=12)),
                ('equity', models.DecimalField(decimal_places=2, max_digits=12)),
                ('balance', models.DecimalField(decimal_places=2, max_digits=12)),
                ('withdrawls', models.DecimalField(decimal_places=2, max_digits=12)),
                ('deposits', models.DecimalField(decimal_places=2, max_digits=12)),
            ],
        ),
        migrations.CreateModel(
            name='Tick',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=8)),
                ('time', models.DateTimeField()),
                ('ask', models.DecimalField(decimal_places=6, max_digits=12)),
                ('bid', models.DecimalField(decimal_places=6, max_digits=12)),
                ('acct', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=8)),
                ('openDate', models.DateTimeField(verbose_name='trade opened')),
                ('closeDate', models.DateTimeField(verbose_name='trade closed')),
                ('ticketId', models.PositiveIntegerField()),
                ('acctNumber', models.PositiveIntegerField()),
                ('type', models.PositiveSmallIntegerField()),
                ('openPrice', models.DecimalField(decimal_places=5, max_digits=12)),
                ('closePrice', models.DecimalField(decimal_places=5, max_digits=12)),
                ('profit', models.DecimalField(decimal_places=2, max_digits=12)),
            ],
        ),
    ]
