# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-07 00:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elpheba', '0002_auto_20171206_0148'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='banked',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
            preserve_default=False,
        ),
    ]
