# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-08 11:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elpheba', '0004_transfer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transfer',
            old_name='acctNumber',
            new_name='fromAcct',
        ),
        migrations.AddField(
            model_name='transfer',
            name='toAcct',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
