# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-04 23:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elpheba', '0005_auto_20171208_1123'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='awaitingTransfer',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
