# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-09-03 05:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elpheba', '0006_account_awaitingtransfer'),
    ]

    operations = [
        migrations.CreateModel(
            name='newTrade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timeStamp', models.DateTimeField(auto_now=True)),
                ('symbol', models.CharField(max_length=8)),
                ('openDate', models.DateTimeField(verbose_name='trade opened')),
                ('type', models.PositiveSmallIntegerField()),
                ('openPrice', models.DecimalField(decimal_places=5, max_digits=12)),
                ('closePrice1', models.DecimalField(decimal_places=5, max_digits=12)),
                ('closePrice2', models.DecimalField(decimal_places=5, max_digits=12)),
                ('stopPrice', models.DecimalField(decimal_places=5, max_digits=12)),
                ('size', models.DecimalField(decimal_places=2, max_digits=12)),
            ],
        ),
    ]
