# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-09-03 05:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elpheba', '0007_newtrade'),
    ]

    operations = [
        migrations.AddField(
            model_name='newtrade',
            name='read',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
    ]
