# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-09-03 05:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elpheba', '0008_newtrade_read'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newtrade',
            name='type',
            field=models.CharField(max_length=4),
        ),
    ]
