# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-09-03 06:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elpheba', '0009_auto_20180903_0545'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newtrade',
            name='openDate',
        ),
    ]
